version: "3"
services:
  productdb:
    image: postgres:11
    environment:
      - POSTGRES_DB=cruddb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
  productapi:
    build: './crud'
    container_name: productapi
    restart: always
    depends_on: 
      - productdb
    ports: 
      - 8082:8082