version: '3'
services:
  productdb:
    image: postgres:11
    environment:
      - POSTGRES_DB=cruddb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
  productapi:
    build: './crud'
    container_name: productapi
    environment:
      - DB_HOST=productdb
      - DB_NAME=cruddb
      - DB_USER=admin
      - DB_PASSWORD=123456
      - DB_PORT=5432
    depends_on:
      - productdb
    restart: always
    ports:
      - 8080:8080